defaults: &defaults
  context_to_api_key: <%= ENV["CONTEXT_IO_API_KEY"] %>
  context_to_api_secret: <%= ENV["CONTEXT_IO_API_SECRET"] %>
  context_to_api_account_id: <%= ENV["CONTEXT_IO_API_ACCOUNT_ID"] %>

  smtp_host: <%= ENV["SMTP_HOST"] %>
  smtp_port: <%= ENV["SMTP_PORT"] %>
  smtp_domain: <%= ENV["SMTP_DOMAIN"] %>
  smtp_username: <%= ENV["SMTP_USERNAME"] %>
  smtp_password: <%= ENV["SMTP_PASSWORD"] %>
  smtp_ssl: <%= ENV["SMTP_SSL"] %>
  default_email: 'bravoteam2017@gmail.com'

development:
  <<: *defaults
  secret_key_base: 037eece44e65d4e2cafbf1cbf49bfa61931d65c5d9ae792aa63fb7030cb86072439a98680a3fe5be27f8d4f4f6cc7134e02fa9230d53a8ae69a6e61493dd04d3

test:
  <<: *defaults
  secret_key_base: ca196af3fbbff96bff1bb1abc0e52d89e69c5582bfd3bf3ece2288c6e39be4bdf68e38d82454049a7805ef70310e1f313f9dd95a1e35b11a881341c612109df7

production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
